### ISSUE TITLE
Bizarre result when opening Grafana IP

### ISSUE THREAD

**Issue by demiters** [digitalocean/marketplace-kubernetes#100]
I one-click installed kubernetes-monitoring-stack, got my Grafana IP but opening it reveals this plain html page:
```
<html lang="pt-br"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gazetaweb</title>
    
    
</head>
<body>
    
    

    
    



    Home
</body></html>
```
This is my first contact with Grafana but this seems weird and I'm not sure how to proceed?

**Comment by jgannondo** [comment]
Hi @demiters - I just tried to replicate this issue and couldn’t, based on installing the app on 2 different clusters. 

1 time I added the app to a cluster that had been up for a few minutes, and the other time I added the app at create time. 

Let me know if there is something else I should try in order to replicate this. Happy to try something else if there’s something I’m doing differently than what you’re doing.

Also, are you running an ad blocker by any chance? If yes, could you try again with it turned off and see if you have the same result? This is a guess vs. a known issue, but might be worth a try.

Best,

John

**Comment by lowercase00** [comment]
Also happened here, but it went to another website, as if the IP was throwing me somewhere else. Already deleted my cluster, my just so you guys now.
